### ISSUE TITLE
Compile task modifies RbConfig values

### ISSUE THREAD

**Issue by bjfish** [rake-compiler/rake-compiler#202]
The compile task currently modifies `RbConfig` values which should be avoided since these are intended to be read only and can cause issues for other users: https://github.com/rake-compiler/rake-compiler/blob/2b146623f239d490048bfe3cbe83785ac27ca040/lib/rake/extensiontask.rb#L148-L151

**Comment by eregon** [comment]
For context, this caused a fairly complex issue in TruffleRuby: https://github.com/oracle/truffleruby/issues/2586
RubyGems uses `RbConfig::CONFIG['sitelibdir']` to find out the initial load path (https://github.com/rubygems/rubygems/blob/c98464e8e859157375177d2b88d9ee01c1355d3f/lib/rubygems.rb#L573-L581), and because that path is changed by rake compiler it doesn't find it anymore, and insert incorrectly in the $LOAD_PATH, loading incorrect gem versions.
This could happen on CRuby too with `--disable-gems` but luckily it does not thanks to CRuby setting the `@gem_prelude_index`, a pretty well hidden "hack" which saves CRuby here.
TruffleRuby will do the same for compatibility, but I believe no gem should mutate `RbConfig` as it can cause issue by anything else using it.

**Comment by eregon** [comment]
This issue was introduced in https://github.com/rake-compiler/rake-compiler/commit/f48d669861583d6fb9c25accb03c1cc2a3292ea6, cc @larskanis

**Comment by eregon** [comment]
In particular this breaks using Bundler (except the Bundler shipped with TruffleRuby, that works fine because there is then a single Bundler version) + the latest TruffleRuby release (22.0), and that's only fixable here.

**Comment by kou** [comment]
@larskanis Can we use `make install sitearchdir=...` instead of rewriting `RbConfig::CONFIG["sitearchdir"]`?

**Comment by larskanis** [comment]
As written in #191, rubygems is using the [same mechanism](https://github.com/rubygems/rubygems/blob/17904c6312bf773e3e3b62589efd4e663f180c21/lib/rubygems/ext/ext_conf_builder.rb#L28-L34) of changing `RbConfig` values when installing gems. That's why I didn't had a bad conscience proposing this.

> Can we use `make install sitearchdir=...` instead of rewriting `RbConfig::CONFIG["sitearchdir"]`?

I think so. `mkmf.rb` seems to not use the variables for anything but passing it into the Makefile. This could make the siteconf file obsolete.

**Comment by eregon** [comment]
Right, it is unfortunate RubyGems uses that, and it seems from a long time ago.
The only "advantage" is RubyGems is fully loaded by the time it uses that code so it doesn't trigger the issue of RubyGems not finding where to insert in `$LOAD_PATH`.
But of course it could break anything else depending on RbConfig::CONFIG values being correct.
I'll file an issue to RubyGems about that.

> I think so. `mkmf.rb` seems to not use the variables for anything but passing it into the Makefile. This could make the siteconf file obsolete.

That would be great :)

**Comment by kou** [comment]
Could @bjfish , @eregon or someone try implementing https://github.com/rake-compiler/rake-compiler/issues/202#issuecomment-1046163347 approach and confirm whether the approach works with TruffleRuby?

**Comment by eregon** [comment]
PR to fix it in RubyGems: https://github.com/rubygems/rubygems/pull/5626
@larskanis Could you do the same here?
